services:
  db:
    image: postgres:14
    container_name: postgress_yuemnoi
    restart: always
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"

volumes:
  postgres_data:
