// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0
// source: proto/reserve/reserve.proto

package yuemnoi_reserve

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestStatus int32

const (
	RequestStatus_REJECTED RequestStatus = 0
	RequestStatus_PENDING  RequestStatus = 1
	RequestStatus_ACCEPTED RequestStatus = 2
)

// Enum value maps for RequestStatus.
var (
	RequestStatus_name = map[int32]string{
		0: "REJECTED",
		1: "PENDING",
		2: "ACCEPTED",
	}
	RequestStatus_value = map[string]int32{
		"REJECTED": 0,
		"PENDING":  1,
		"ACCEPTED": 2,
	}
)

func (x RequestStatus) Enum() *RequestStatus {
	p := new(RequestStatus)
	*p = x
	return p
}

func (x RequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_reserve_reserve_proto_enumTypes[0].Descriptor()
}

func (RequestStatus) Type() protoreflect.EnumType {
	return &file_proto_reserve_reserve_proto_enumTypes[0]
}

func (x RequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestStatus.Descriptor instead.
func (RequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_reserve_reserve_proto_rawDescGZIP(), []int{0}
}

type BorrowingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LendingUserId   uint64        `protobuf:"varint,2,opt,name=lending_user_id,json=lendingUserId,proto3" json:"lending_user_id,omitempty"`
	BorrowingUserId uint64        `protobuf:"varint,3,opt,name=borrowing_user_id,json=borrowingUserId,proto3" json:"borrowing_user_id,omitempty"`
	LendingPostId   uint64        `protobuf:"varint,4,opt,name=lending_post_id,json=lendingPostId,proto3" json:"lending_post_id,omitempty"`
	BorrowingPostId uint64        `protobuf:"varint,5,opt,name=borrowing_post_id,json=borrowingPostId,proto3" json:"borrowing_post_id,omitempty"`
	Status          RequestStatus `protobuf:"varint,6,opt,name=status,proto3,enum=RequestStatus" json:"status,omitempty"`
	ActiveStatus    bool          `protobuf:"varint,7,opt,name=active_status,json=activeStatus,proto3" json:"active_status,omitempty"`
}

func (x *BorrowingRequest) Reset() {
	*x = BorrowingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reserve_reserve_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowingRequest) ProtoMessage() {}

func (x *BorrowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserve_reserve_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowingRequest.ProtoReflect.Descriptor instead.
func (*BorrowingRequest) Descriptor() ([]byte, []int) {
	return file_proto_reserve_reserve_proto_rawDescGZIP(), []int{0}
}

func (x *BorrowingRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BorrowingRequest) GetLendingUserId() uint64 {
	if x != nil {
		return x.LendingUserId
	}
	return 0
}

func (x *BorrowingRequest) GetBorrowingUserId() uint64 {
	if x != nil {
		return x.BorrowingUserId
	}
	return 0
}

func (x *BorrowingRequest) GetLendingPostId() uint64 {
	if x != nil {
		return x.LendingPostId
	}
	return 0
}

func (x *BorrowingRequest) GetBorrowingPostId() uint64 {
	if x != nil {
		return x.BorrowingPostId
	}
	return 0
}

func (x *BorrowingRequest) GetStatus() RequestStatus {
	if x != nil {
		return x.Status
	}
	return RequestStatus_REJECTED
}

func (x *BorrowingRequest) GetActiveStatus() bool {
	if x != nil {
		return x.ActiveStatus
	}
	return false
}

type CreateBorrowingRequestInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LendingUserId   uint64 `protobuf:"varint,1,opt,name=lending_user_id,json=lendingUserId,proto3" json:"lending_user_id,omitempty"`
	BorrowingUserId uint64 `protobuf:"varint,2,opt,name=borrowing_user_id,json=borrowingUserId,proto3" json:"borrowing_user_id,omitempty"`
	LendingPostId   uint64 `protobuf:"varint,3,opt,name=lending_post_id,json=lendingPostId,proto3" json:"lending_post_id,omitempty"`
	BorrowingPostId uint64 `protobuf:"varint,4,opt,name=borrowing_post_id,json=borrowingPostId,proto3" json:"borrowing_post_id,omitempty"`
}

func (x *CreateBorrowingRequestInput) Reset() {
	*x = CreateBorrowingRequestInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reserve_reserve_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBorrowingRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBorrowingRequestInput) ProtoMessage() {}

func (x *CreateBorrowingRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserve_reserve_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBorrowingRequestInput.ProtoReflect.Descriptor instead.
func (*CreateBorrowingRequestInput) Descriptor() ([]byte, []int) {
	return file_proto_reserve_reserve_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBorrowingRequestInput) GetLendingUserId() uint64 {
	if x != nil {
		return x.LendingUserId
	}
	return 0
}

func (x *CreateBorrowingRequestInput) GetBorrowingUserId() uint64 {
	if x != nil {
		return x.BorrowingUserId
	}
	return 0
}

func (x *CreateBorrowingRequestInput) GetLendingPostId() uint64 {
	if x != nil {
		return x.LendingPostId
	}
	return 0
}

func (x *CreateBorrowingRequestInput) GetBorrowingPostId() uint64 {
	if x != nil {
		return x.BorrowingPostId
	}
	return 0
}

type CreateBorrowingRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateBorrowingRequestResponse) Reset() {
	*x = CreateBorrowingRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reserve_reserve_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBorrowingRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBorrowingRequestResponse) ProtoMessage() {}

func (x *CreateBorrowingRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserve_reserve_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBorrowingRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateBorrowingRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_reserve_reserve_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBorrowingRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetBorrowingRequestInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBorrowingRequestInput) Reset() {
	*x = GetBorrowingRequestInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reserve_reserve_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBorrowingRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBorrowingRequestInput) ProtoMessage() {}

func (x *GetBorrowingRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserve_reserve_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBorrowingRequestInput.ProtoReflect.Descriptor instead.
func (*GetBorrowingRequestInput) Descriptor() ([]byte, []int) {
	return file_proto_reserve_reserve_proto_rawDescGZIP(), []int{3}
}

func (x *GetBorrowingRequestInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AcceptBorrowingRequestInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AcceptBorrowingRequestInput) Reset() {
	*x = AcceptBorrowingRequestInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reserve_reserve_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptBorrowingRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptBorrowingRequestInput) ProtoMessage() {}

func (x *AcceptBorrowingRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserve_reserve_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptBorrowingRequestInput.ProtoReflect.Descriptor instead.
func (*AcceptBorrowingRequestInput) Descriptor() ([]byte, []int) {
	return file_proto_reserve_reserve_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptBorrowingRequestInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RejectBorrowingRequestInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RejectBorrowingRequestInput) Reset() {
	*x = RejectBorrowingRequestInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reserve_reserve_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejectBorrowingRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectBorrowingRequestInput) ProtoMessage() {}

func (x *RejectBorrowingRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserve_reserve_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectBorrowingRequestInput.ProtoReflect.Descriptor instead.
func (*RejectBorrowingRequestInput) Descriptor() ([]byte, []int) {
	return file_proto_reserve_reserve_proto_rawDescGZIP(), []int{5}
}

func (x *RejectBorrowingRequestInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReturnItemBorrowingRequestInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReturnItemBorrowingRequestInput) Reset() {
	*x = ReturnItemBorrowingRequestInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reserve_reserve_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnItemBorrowingRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnItemBorrowingRequestInput) ProtoMessage() {}

func (x *ReturnItemBorrowingRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserve_reserve_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnItemBorrowingRequestInput.ProtoReflect.Descriptor instead.
func (*ReturnItemBorrowingRequestInput) Descriptor() ([]byte, []int) {
	return file_proto_reserve_reserve_proto_rawDescGZIP(), []int{6}
}

func (x *ReturnItemBorrowingRequestInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// The reserve message representing the structure of the Reserve object
type LendingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LendingUserId   uint64        `protobuf:"varint,2,opt,name=lending_user_id,json=lendingUserId,proto3" json:"lending_user_id,omitempty"`
	BorrowingUserId uint64        `protobuf:"varint,3,opt,name=borrowing_user_id,json=borrowingUserId,proto3" json:"borrowing_user_id,omitempty"`
	PostId          uint64        `protobuf:"varint,4,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Status          RequestStatus `protobuf:"varint,5,opt,name=status,proto3,enum=RequestStatus" json:"status,omitempty"`
	ActiveStatus    bool          `protobuf:"varint,6,opt,name=activeStatus,proto3" json:"activeStatus,omitempty"`
}

func (x *LendingRequest) Reset() {
	*x = LendingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reserve_reserve_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LendingRequest) ProtoMessage() {}

func (x *LendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserve_reserve_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LendingRequest.ProtoReflect.Descriptor instead.
func (*LendingRequest) Descriptor() ([]byte, []int) {
	return file_proto_reserve_reserve_proto_rawDescGZIP(), []int{7}
}

func (x *LendingRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LendingRequest) GetLendingUserId() uint64 {
	if x != nil {
		return x.LendingUserId
	}
	return 0
}

func (x *LendingRequest) GetBorrowingUserId() uint64 {
	if x != nil {
		return x.BorrowingUserId
	}
	return 0
}

func (x *LendingRequest) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *LendingRequest) GetStatus() RequestStatus {
	if x != nil {
		return x.Status
	}
	return RequestStatus_REJECTED
}

func (x *LendingRequest) GetActiveStatus() bool {
	if x != nil {
		return x.ActiveStatus
	}
	return false
}

// Request message for creating a new Reserve
type CreateLendingRequestInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LendingUserId   uint64 `protobuf:"varint,1,opt,name=lending_user_id,json=lendingUserId,proto3" json:"lending_user_id,omitempty"`
	BorrowingUserId uint64 `protobuf:"varint,2,opt,name=borrowing_user_id,json=borrowingUserId,proto3" json:"borrowing_user_id,omitempty"`
	PostId          uint64 `protobuf:"varint,3,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
}

func (x *CreateLendingRequestInput) Reset() {
	*x = CreateLendingRequestInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reserve_reserve_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLendingRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLendingRequestInput) ProtoMessage() {}

func (x *CreateLendingRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserve_reserve_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLendingRequestInput.ProtoReflect.Descriptor instead.
func (*CreateLendingRequestInput) Descriptor() ([]byte, []int) {
	return file_proto_reserve_reserve_proto_rawDescGZIP(), []int{8}
}

func (x *CreateLendingRequestInput) GetLendingUserId() uint64 {
	if x != nil {
		return x.LendingUserId
	}
	return 0
}

func (x *CreateLendingRequestInput) GetBorrowingUserId() uint64 {
	if x != nil {
		return x.BorrowingUserId
	}
	return 0
}

func (x *CreateLendingRequestInput) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// Response message for the CreateReserve service
type CreateLendingRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateLendingRequestResponse) Reset() {
	*x = CreateLendingRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reserve_reserve_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLendingRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLendingRequestResponse) ProtoMessage() {}

func (x *CreateLendingRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserve_reserve_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLendingRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateLendingRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_reserve_reserve_proto_rawDescGZIP(), []int{9}
}

func (x *CreateLendingRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request message for fetching Reserve details
type GetLendingRequestInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetLendingRequestInput) Reset() {
	*x = GetLendingRequestInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reserve_reserve_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLendingRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLendingRequestInput) ProtoMessage() {}

func (x *GetLendingRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserve_reserve_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLendingRequestInput.ProtoReflect.Descriptor instead.
func (*GetLendingRequestInput) Descriptor() ([]byte, []int) {
	return file_proto_reserve_reserve_proto_rawDescGZIP(), []int{10}
}

func (x *GetLendingRequestInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RejectLendingRequestInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RejectLendingRequestInput) Reset() {
	*x = RejectLendingRequestInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reserve_reserve_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejectLendingRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectLendingRequestInput) ProtoMessage() {}

func (x *RejectLendingRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserve_reserve_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectLendingRequestInput.ProtoReflect.Descriptor instead.
func (*RejectLendingRequestInput) Descriptor() ([]byte, []int) {
	return file_proto_reserve_reserve_proto_rawDescGZIP(), []int{11}
}

func (x *RejectLendingRequestInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AcceptLendingRequestInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AcceptLendingRequestInput) Reset() {
	*x = AcceptLendingRequestInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reserve_reserve_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptLendingRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptLendingRequestInput) ProtoMessage() {}

func (x *AcceptLendingRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserve_reserve_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptLendingRequestInput.ProtoReflect.Descriptor instead.
func (*AcceptLendingRequestInput) Descriptor() ([]byte, []int) {
	return file_proto_reserve_reserve_proto_rawDescGZIP(), []int{12}
}

func (x *AcceptLendingRequestInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReturnItemLendingRequestInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReturnItemLendingRequestInput) Reset() {
	*x = ReturnItemLendingRequestInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reserve_reserve_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnItemLendingRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnItemLendingRequestInput) ProtoMessage() {}

func (x *ReturnItemLendingRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reserve_reserve_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnItemLendingRequestInput.ProtoReflect.Descriptor instead.
func (*ReturnItemLendingRequestInput) Descriptor() ([]byte, []int) {
	return file_proto_reserve_reserve_proto_rawDescGZIP(), []int{13}
}

func (x *ReturnItemLendingRequestInput) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_reserve_reserve_proto protoreflect.FileDescriptor

var file_proto_reserve_reserve_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x2f,
	0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x02,
	0x0a, 0x10, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6c, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x62, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0d, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x2a,
	0x0a, 0x11, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x62, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xc5, 0x01, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0d, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x2a, 0x0a, 0x11, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x62, 0x6f, 0x72, 0x72,
	0x6f, 0x77, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6c,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67,
	0x5f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f,
	0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22,
	0x3a, 0x0a, 0x1e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x1b, 0x41, 0x63, 0x63, 0x65, 0x70,
	0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x1b, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74,
	0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x1f, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x49,
	0x74, 0x65, 0x6d, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0xd9, 0x01, 0x0a, 0x0e, 0x4c, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6c,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f,
	0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x88, 0x01, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6c, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x62, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22,
	0x38, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x28, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x19, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2b, 0x0a, 0x19, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a,
	0x1d, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x2a, 0x38,
	0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0c, 0x0a, 0x08, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x43,
	0x43, 0x45, 0x50, 0x54, 0x45, 0x44, 0x10, 0x02, 0x32, 0x9d, 0x03, 0x0a, 0x10, 0x42, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a,
	0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x49,
	0x64, 0x12, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x11, 0x2e, 0x42,
	0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x49, 0x0a, 0x16, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x11, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x49, 0x0a, 0x16, 0x52, 0x65,
	0x6a, 0x65, 0x63, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x42, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x1a, 0x11, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x51, 0x0a, 0x1a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x49,
	0x74, 0x65, 0x6d, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x49, 0x74, 0x65, 0x6d,
	0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x11, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x87, 0x03, 0x0a, 0x0e, 0x52, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x14, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a,
	0x1d, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x43, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x1a, 0x0f, 0x2e, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x14, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x4c,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x2e,
	0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x0f, 0x2e, 0x4c, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x14,
	0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4c, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x1a, 0x0f, 0x2e, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x18, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x49, 0x74, 0x65,
	0x6d, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a,
	0x0f, 0x2e, 0x4c, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x00, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x4b, 0x4b, 0x68, 0x69, 0x6d, 0x6d, 0x6f, 0x6f, 0x6e, 0x2f, 0x79, 0x75, 0x65, 0x6d, 0x6e,
	0x6f, 0x69, 0x2d, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_reserve_reserve_proto_rawDescOnce sync.Once
	file_proto_reserve_reserve_proto_rawDescData = file_proto_reserve_reserve_proto_rawDesc
)

func file_proto_reserve_reserve_proto_rawDescGZIP() []byte {
	file_proto_reserve_reserve_proto_rawDescOnce.Do(func() {
		file_proto_reserve_reserve_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_reserve_reserve_proto_rawDescData)
	})
	return file_proto_reserve_reserve_proto_rawDescData
}

var file_proto_reserve_reserve_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_reserve_reserve_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_reserve_reserve_proto_goTypes = []any{
	(RequestStatus)(0),                      // 0: RequestStatus
	(*BorrowingRequest)(nil),                // 1: BorrowingRequest
	(*CreateBorrowingRequestInput)(nil),     // 2: CreateBorrowingRequestInput
	(*CreateBorrowingRequestResponse)(nil),  // 3: CreateBorrowingRequestResponse
	(*GetBorrowingRequestInput)(nil),        // 4: GetBorrowingRequestInput
	(*AcceptBorrowingRequestInput)(nil),     // 5: AcceptBorrowingRequestInput
	(*RejectBorrowingRequestInput)(nil),     // 6: RejectBorrowingRequestInput
	(*ReturnItemBorrowingRequestInput)(nil), // 7: ReturnItemBorrowingRequestInput
	(*LendingRequest)(nil),                  // 8: LendingRequest
	(*CreateLendingRequestInput)(nil),       // 9: CreateLendingRequestInput
	(*CreateLendingRequestResponse)(nil),    // 10: CreateLendingRequestResponse
	(*GetLendingRequestInput)(nil),          // 11: GetLendingRequestInput
	(*RejectLendingRequestInput)(nil),       // 12: RejectLendingRequestInput
	(*AcceptLendingRequestInput)(nil),       // 13: AcceptLendingRequestInput
	(*ReturnItemLendingRequestInput)(nil),   // 14: ReturnItemLendingRequestInput
}
var file_proto_reserve_reserve_proto_depIdxs = []int32{
	0,  // 0: BorrowingRequest.status:type_name -> RequestStatus
	0,  // 1: LendingRequest.status:type_name -> RequestStatus
	2,  // 2: BorrowingService.CreateBorrowingRequest:input_type -> CreateBorrowingRequestInput
	4,  // 3: BorrowingService.GetBorrowingRequestById:input_type -> GetBorrowingRequestInput
	5,  // 4: BorrowingService.AcceptBorrowingRequest:input_type -> AcceptBorrowingRequestInput
	6,  // 5: BorrowingService.RejectBorrowingRequest:input_type -> RejectBorrowingRequestInput
	7,  // 6: BorrowingService.ReturnItemBorrowingRequest:input_type -> ReturnItemBorrowingRequestInput
	9,  // 7: ReserveService.CreateLendingRequest:input_type -> CreateLendingRequestInput
	11, // 8: ReserveService.GetLendingRequestById:input_type -> GetLendingRequestInput
	12, // 9: ReserveService.RejectLendingRequest:input_type -> RejectLendingRequestInput
	13, // 10: ReserveService.AcceptLendingRequest:input_type -> AcceptLendingRequestInput
	14, // 11: ReserveService.ReturnItemLendingRequest:input_type -> ReturnItemLendingRequestInput
	3,  // 12: BorrowingService.CreateBorrowingRequest:output_type -> CreateBorrowingRequestResponse
	1,  // 13: BorrowingService.GetBorrowingRequestById:output_type -> BorrowingRequest
	1,  // 14: BorrowingService.AcceptBorrowingRequest:output_type -> BorrowingRequest
	1,  // 15: BorrowingService.RejectBorrowingRequest:output_type -> BorrowingRequest
	1,  // 16: BorrowingService.ReturnItemBorrowingRequest:output_type -> BorrowingRequest
	10, // 17: ReserveService.CreateLendingRequest:output_type -> CreateLendingRequestResponse
	8,  // 18: ReserveService.GetLendingRequestById:output_type -> LendingRequest
	8,  // 19: ReserveService.RejectLendingRequest:output_type -> LendingRequest
	8,  // 20: ReserveService.AcceptLendingRequest:output_type -> LendingRequest
	8,  // 21: ReserveService.ReturnItemLendingRequest:output_type -> LendingRequest
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_reserve_reserve_proto_init() }
func file_proto_reserve_reserve_proto_init() {
	if File_proto_reserve_reserve_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_reserve_reserve_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BorrowingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reserve_reserve_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBorrowingRequestInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reserve_reserve_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBorrowingRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reserve_reserve_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetBorrowingRequestInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reserve_reserve_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AcceptBorrowingRequestInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reserve_reserve_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RejectBorrowingRequestInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reserve_reserve_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ReturnItemBorrowingRequestInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reserve_reserve_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*LendingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reserve_reserve_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CreateLendingRequestInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reserve_reserve_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CreateLendingRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reserve_reserve_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GetLendingRequestInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reserve_reserve_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*RejectLendingRequestInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reserve_reserve_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*AcceptLendingRequestInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reserve_reserve_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*ReturnItemLendingRequestInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_reserve_reserve_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_reserve_reserve_proto_goTypes,
		DependencyIndexes: file_proto_reserve_reserve_proto_depIdxs,
		EnumInfos:         file_proto_reserve_reserve_proto_enumTypes,
		MessageInfos:      file_proto_reserve_reserve_proto_msgTypes,
	}.Build()
	File_proto_reserve_reserve_proto = out.File
	file_proto_reserve_reserve_proto_rawDesc = nil
	file_proto_reserve_reserve_proto_goTypes = nil
	file_proto_reserve_reserve_proto_depIdxs = nil
}
