// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/reserve/reserve.proto

package yuemnoi_reserve

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BorrowingService_CreateBorrowingRequest_FullMethodName     = "/BorrowingService/CreateBorrowingRequest"
	BorrowingService_GetBorrowingRequestById_FullMethodName    = "/BorrowingService/GetBorrowingRequestById"
	BorrowingService_AcceptBorrowingRequest_FullMethodName     = "/BorrowingService/AcceptBorrowingRequest"
	BorrowingService_RejectBorrowingRequest_FullMethodName     = "/BorrowingService/RejectBorrowingRequest"
	BorrowingService_ReturnItemBorrowingRequest_FullMethodName = "/BorrowingService/ReturnItemBorrowingRequest"
	BorrowingService_GetBorrowingRequests_FullMethodName       = "/BorrowingService/GetBorrowingRequests"
)

// BorrowingServiceClient is the client API for BorrowingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BorrowingServiceClient interface {
	CreateBorrowingRequest(ctx context.Context, in *CreateBorrowingRequestInput, opts ...grpc.CallOption) (*CreateBorrowingRequestResponse, error)
	GetBorrowingRequestById(ctx context.Context, in *GetBorrowingRequestInput, opts ...grpc.CallOption) (*BorrowingRequest, error)
	AcceptBorrowingRequest(ctx context.Context, in *AcceptBorrowingRequestInput, opts ...grpc.CallOption) (*BorrowingRequest, error)
	RejectBorrowingRequest(ctx context.Context, in *RejectBorrowingRequestInput, opts ...grpc.CallOption) (*BorrowingRequest, error)
	ReturnItemBorrowingRequest(ctx context.Context, in *ReturnItemBorrowingRequestInput, opts ...grpc.CallOption) (*BorrowingRequest, error)
	GetBorrowingRequests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BorrowingRequestList, error)
}

type borrowingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBorrowingServiceClient(cc grpc.ClientConnInterface) BorrowingServiceClient {
	return &borrowingServiceClient{cc}
}

func (c *borrowingServiceClient) CreateBorrowingRequest(ctx context.Context, in *CreateBorrowingRequestInput, opts ...grpc.CallOption) (*CreateBorrowingRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBorrowingRequestResponse)
	err := c.cc.Invoke(ctx, BorrowingService_CreateBorrowingRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowingServiceClient) GetBorrowingRequestById(ctx context.Context, in *GetBorrowingRequestInput, opts ...grpc.CallOption) (*BorrowingRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BorrowingRequest)
	err := c.cc.Invoke(ctx, BorrowingService_GetBorrowingRequestById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowingServiceClient) AcceptBorrowingRequest(ctx context.Context, in *AcceptBorrowingRequestInput, opts ...grpc.CallOption) (*BorrowingRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BorrowingRequest)
	err := c.cc.Invoke(ctx, BorrowingService_AcceptBorrowingRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowingServiceClient) RejectBorrowingRequest(ctx context.Context, in *RejectBorrowingRequestInput, opts ...grpc.CallOption) (*BorrowingRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BorrowingRequest)
	err := c.cc.Invoke(ctx, BorrowingService_RejectBorrowingRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowingServiceClient) ReturnItemBorrowingRequest(ctx context.Context, in *ReturnItemBorrowingRequestInput, opts ...grpc.CallOption) (*BorrowingRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BorrowingRequest)
	err := c.cc.Invoke(ctx, BorrowingService_ReturnItemBorrowingRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *borrowingServiceClient) GetBorrowingRequests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BorrowingRequestList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BorrowingRequestList)
	err := c.cc.Invoke(ctx, BorrowingService_GetBorrowingRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BorrowingServiceServer is the server API for BorrowingService service.
// All implementations must embed UnimplementedBorrowingServiceServer
// for forward compatibility.
type BorrowingServiceServer interface {
	CreateBorrowingRequest(context.Context, *CreateBorrowingRequestInput) (*CreateBorrowingRequestResponse, error)
	GetBorrowingRequestById(context.Context, *GetBorrowingRequestInput) (*BorrowingRequest, error)
	AcceptBorrowingRequest(context.Context, *AcceptBorrowingRequestInput) (*BorrowingRequest, error)
	RejectBorrowingRequest(context.Context, *RejectBorrowingRequestInput) (*BorrowingRequest, error)
	ReturnItemBorrowingRequest(context.Context, *ReturnItemBorrowingRequestInput) (*BorrowingRequest, error)
	GetBorrowingRequests(context.Context, *Empty) (*BorrowingRequestList, error)
	mustEmbedUnimplementedBorrowingServiceServer()
}

// UnimplementedBorrowingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBorrowingServiceServer struct{}

func (UnimplementedBorrowingServiceServer) CreateBorrowingRequest(context.Context, *CreateBorrowingRequestInput) (*CreateBorrowingRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBorrowingRequest not implemented")
}
func (UnimplementedBorrowingServiceServer) GetBorrowingRequestById(context.Context, *GetBorrowingRequestInput) (*BorrowingRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBorrowingRequestById not implemented")
}
func (UnimplementedBorrowingServiceServer) AcceptBorrowingRequest(context.Context, *AcceptBorrowingRequestInput) (*BorrowingRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptBorrowingRequest not implemented")
}
func (UnimplementedBorrowingServiceServer) RejectBorrowingRequest(context.Context, *RejectBorrowingRequestInput) (*BorrowingRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectBorrowingRequest not implemented")
}
func (UnimplementedBorrowingServiceServer) ReturnItemBorrowingRequest(context.Context, *ReturnItemBorrowingRequestInput) (*BorrowingRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnItemBorrowingRequest not implemented")
}
func (UnimplementedBorrowingServiceServer) GetBorrowingRequests(context.Context, *Empty) (*BorrowingRequestList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBorrowingRequests not implemented")
}
func (UnimplementedBorrowingServiceServer) mustEmbedUnimplementedBorrowingServiceServer() {}
func (UnimplementedBorrowingServiceServer) testEmbeddedByValue()                          {}

// UnsafeBorrowingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BorrowingServiceServer will
// result in compilation errors.
type UnsafeBorrowingServiceServer interface {
	mustEmbedUnimplementedBorrowingServiceServer()
}

func RegisterBorrowingServiceServer(s grpc.ServiceRegistrar, srv BorrowingServiceServer) {
	// If the following call pancis, it indicates UnimplementedBorrowingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BorrowingService_ServiceDesc, srv)
}

func _BorrowingService_CreateBorrowingRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBorrowingRequestInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowingServiceServer).CreateBorrowingRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BorrowingService_CreateBorrowingRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowingServiceServer).CreateBorrowingRequest(ctx, req.(*CreateBorrowingRequestInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BorrowingService_GetBorrowingRequestById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBorrowingRequestInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowingServiceServer).GetBorrowingRequestById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BorrowingService_GetBorrowingRequestById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowingServiceServer).GetBorrowingRequestById(ctx, req.(*GetBorrowingRequestInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BorrowingService_AcceptBorrowingRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptBorrowingRequestInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowingServiceServer).AcceptBorrowingRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BorrowingService_AcceptBorrowingRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowingServiceServer).AcceptBorrowingRequest(ctx, req.(*AcceptBorrowingRequestInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BorrowingService_RejectBorrowingRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectBorrowingRequestInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowingServiceServer).RejectBorrowingRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BorrowingService_RejectBorrowingRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowingServiceServer).RejectBorrowingRequest(ctx, req.(*RejectBorrowingRequestInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BorrowingService_ReturnItemBorrowingRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnItemBorrowingRequestInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowingServiceServer).ReturnItemBorrowingRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BorrowingService_ReturnItemBorrowingRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowingServiceServer).ReturnItemBorrowingRequest(ctx, req.(*ReturnItemBorrowingRequestInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BorrowingService_GetBorrowingRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BorrowingServiceServer).GetBorrowingRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BorrowingService_GetBorrowingRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BorrowingServiceServer).GetBorrowingRequests(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BorrowingService_ServiceDesc is the grpc.ServiceDesc for BorrowingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BorrowingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BorrowingService",
	HandlerType: (*BorrowingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBorrowingRequest",
			Handler:    _BorrowingService_CreateBorrowingRequest_Handler,
		},
		{
			MethodName: "GetBorrowingRequestById",
			Handler:    _BorrowingService_GetBorrowingRequestById_Handler,
		},
		{
			MethodName: "AcceptBorrowingRequest",
			Handler:    _BorrowingService_AcceptBorrowingRequest_Handler,
		},
		{
			MethodName: "RejectBorrowingRequest",
			Handler:    _BorrowingService_RejectBorrowingRequest_Handler,
		},
		{
			MethodName: "ReturnItemBorrowingRequest",
			Handler:    _BorrowingService_ReturnItemBorrowingRequest_Handler,
		},
		{
			MethodName: "GetBorrowingRequests",
			Handler:    _BorrowingService_GetBorrowingRequests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/reserve/reserve.proto",
}

const (
	ReserveService_CreateLendingRequest_FullMethodName     = "/ReserveService/CreateLendingRequest"
	ReserveService_GetLendingRequestById_FullMethodName    = "/ReserveService/GetLendingRequestById"
	ReserveService_RejectLendingRequest_FullMethodName     = "/ReserveService/RejectLendingRequest"
	ReserveService_AcceptLendingRequest_FullMethodName     = "/ReserveService/AcceptLendingRequest"
	ReserveService_ReturnItemLendingRequest_FullMethodName = "/ReserveService/ReturnItemLendingRequest"
	ReserveService_GetLendingRequests_FullMethodName       = "/ReserveService/GetLendingRequests"
)

// ReserveServiceClient is the client API for ReserveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReserveServiceClient interface {
	CreateLendingRequest(ctx context.Context, in *CreateLendingRequestInput, opts ...grpc.CallOption) (*CreateLendingRequestResponse, error)
	GetLendingRequestById(ctx context.Context, in *GetLendingRequestInput, opts ...grpc.CallOption) (*LendingRequest, error)
	RejectLendingRequest(ctx context.Context, in *RejectLendingRequestInput, opts ...grpc.CallOption) (*LendingRequest, error)
	AcceptLendingRequest(ctx context.Context, in *AcceptLendingRequestInput, opts ...grpc.CallOption) (*LendingRequest, error)
	ReturnItemLendingRequest(ctx context.Context, in *ReturnItemLendingRequestInput, opts ...grpc.CallOption) (*LendingRequest, error)
	GetLendingRequests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LendingRequestList, error)
}

type reserveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReserveServiceClient(cc grpc.ClientConnInterface) ReserveServiceClient {
	return &reserveServiceClient{cc}
}

func (c *reserveServiceClient) CreateLendingRequest(ctx context.Context, in *CreateLendingRequestInput, opts ...grpc.CallOption) (*CreateLendingRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLendingRequestResponse)
	err := c.cc.Invoke(ctx, ReserveService_CreateLendingRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reserveServiceClient) GetLendingRequestById(ctx context.Context, in *GetLendingRequestInput, opts ...grpc.CallOption) (*LendingRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LendingRequest)
	err := c.cc.Invoke(ctx, ReserveService_GetLendingRequestById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reserveServiceClient) RejectLendingRequest(ctx context.Context, in *RejectLendingRequestInput, opts ...grpc.CallOption) (*LendingRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LendingRequest)
	err := c.cc.Invoke(ctx, ReserveService_RejectLendingRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reserveServiceClient) AcceptLendingRequest(ctx context.Context, in *AcceptLendingRequestInput, opts ...grpc.CallOption) (*LendingRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LendingRequest)
	err := c.cc.Invoke(ctx, ReserveService_AcceptLendingRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reserveServiceClient) ReturnItemLendingRequest(ctx context.Context, in *ReturnItemLendingRequestInput, opts ...grpc.CallOption) (*LendingRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LendingRequest)
	err := c.cc.Invoke(ctx, ReserveService_ReturnItemLendingRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reserveServiceClient) GetLendingRequests(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LendingRequestList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LendingRequestList)
	err := c.cc.Invoke(ctx, ReserveService_GetLendingRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReserveServiceServer is the server API for ReserveService service.
// All implementations must embed UnimplementedReserveServiceServer
// for forward compatibility.
type ReserveServiceServer interface {
	CreateLendingRequest(context.Context, *CreateLendingRequestInput) (*CreateLendingRequestResponse, error)
	GetLendingRequestById(context.Context, *GetLendingRequestInput) (*LendingRequest, error)
	RejectLendingRequest(context.Context, *RejectLendingRequestInput) (*LendingRequest, error)
	AcceptLendingRequest(context.Context, *AcceptLendingRequestInput) (*LendingRequest, error)
	ReturnItemLendingRequest(context.Context, *ReturnItemLendingRequestInput) (*LendingRequest, error)
	GetLendingRequests(context.Context, *Empty) (*LendingRequestList, error)
	mustEmbedUnimplementedReserveServiceServer()
}

// UnimplementedReserveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReserveServiceServer struct{}

func (UnimplementedReserveServiceServer) CreateLendingRequest(context.Context, *CreateLendingRequestInput) (*CreateLendingRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLendingRequest not implemented")
}
func (UnimplementedReserveServiceServer) GetLendingRequestById(context.Context, *GetLendingRequestInput) (*LendingRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLendingRequestById not implemented")
}
func (UnimplementedReserveServiceServer) RejectLendingRequest(context.Context, *RejectLendingRequestInput) (*LendingRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectLendingRequest not implemented")
}
func (UnimplementedReserveServiceServer) AcceptLendingRequest(context.Context, *AcceptLendingRequestInput) (*LendingRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptLendingRequest not implemented")
}
func (UnimplementedReserveServiceServer) ReturnItemLendingRequest(context.Context, *ReturnItemLendingRequestInput) (*LendingRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnItemLendingRequest not implemented")
}
func (UnimplementedReserveServiceServer) GetLendingRequests(context.Context, *Empty) (*LendingRequestList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLendingRequests not implemented")
}
func (UnimplementedReserveServiceServer) mustEmbedUnimplementedReserveServiceServer() {}
func (UnimplementedReserveServiceServer) testEmbeddedByValue()                        {}

// UnsafeReserveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReserveServiceServer will
// result in compilation errors.
type UnsafeReserveServiceServer interface {
	mustEmbedUnimplementedReserveServiceServer()
}

func RegisterReserveServiceServer(s grpc.ServiceRegistrar, srv ReserveServiceServer) {
	// If the following call pancis, it indicates UnimplementedReserveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReserveService_ServiceDesc, srv)
}

func _ReserveService_CreateLendingRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLendingRequestInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReserveServiceServer).CreateLendingRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReserveService_CreateLendingRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReserveServiceServer).CreateLendingRequest(ctx, req.(*CreateLendingRequestInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReserveService_GetLendingRequestById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLendingRequestInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReserveServiceServer).GetLendingRequestById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReserveService_GetLendingRequestById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReserveServiceServer).GetLendingRequestById(ctx, req.(*GetLendingRequestInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReserveService_RejectLendingRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectLendingRequestInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReserveServiceServer).RejectLendingRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReserveService_RejectLendingRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReserveServiceServer).RejectLendingRequest(ctx, req.(*RejectLendingRequestInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReserveService_AcceptLendingRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptLendingRequestInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReserveServiceServer).AcceptLendingRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReserveService_AcceptLendingRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReserveServiceServer).AcceptLendingRequest(ctx, req.(*AcceptLendingRequestInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReserveService_ReturnItemLendingRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnItemLendingRequestInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReserveServiceServer).ReturnItemLendingRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReserveService_ReturnItemLendingRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReserveServiceServer).ReturnItemLendingRequest(ctx, req.(*ReturnItemLendingRequestInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReserveService_GetLendingRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReserveServiceServer).GetLendingRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReserveService_GetLendingRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReserveServiceServer).GetLendingRequests(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ReserveService_ServiceDesc is the grpc.ServiceDesc for ReserveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReserveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ReserveService",
	HandlerType: (*ReserveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLendingRequest",
			Handler:    _ReserveService_CreateLendingRequest_Handler,
		},
		{
			MethodName: "GetLendingRequestById",
			Handler:    _ReserveService_GetLendingRequestById_Handler,
		},
		{
			MethodName: "RejectLendingRequest",
			Handler:    _ReserveService_RejectLendingRequest_Handler,
		},
		{
			MethodName: "AcceptLendingRequest",
			Handler:    _ReserveService_AcceptLendingRequest_Handler,
		},
		{
			MethodName: "ReturnItemLendingRequest",
			Handler:    _ReserveService_ReturnItemLendingRequest_Handler,
		},
		{
			MethodName: "GetLendingRequests",
			Handler:    _ReserveService_GetLendingRequests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/reserve/reserve.proto",
}
