appName: reserve
port: 8082
activityLogPort: 8085
postPort: 8081
DB:
  host: localhost
  port: "5434"
  username: youruser
  password: yourpassword
  database: yourdbname
rabbitmqurl: amqps://fdnesexk:oATQpfEYx_9QHrQjv1O9WftUaOSvheub@octopus.rmq3.cloudamqp.com/fdnesexk
